name: Build Doxygen Docs

on:
  push:
    branches: [ doxygen ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        uses: doxygen/action@v1
      - run: doxygen Doxyfile
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
